import pymupdf
import os

pages_text = [
    # Page 1
    "Section II\nAPPAREL, EQUIPMENT AND MATERIALS\n2-01. Apparel, General.--Torn or loose clothes should never be worn. All employees should keep their clothing sewed, patched or in such condition that there are no flopping ends; as loose clothing is neither safe nor comfortable. Safety shoes are recommended for all employees working on floating plant, either in the boatyard or field. (They cost no more than ordinary shoes, and afford maximum protection to the feet.) All safety apparel shall be adjusted and in place before any operation requiring such apparel is commenced.\n\n2-02. Blacksmith aprons shall be worn when;\n(a) Working with molten metal;\n(b) Forging metal (ie) heated and then beaten to shape or size;\n(c) Handling battery acid or caustic.\n\n2-03. Diver's equipment shall be worn whenever work is carried on by hand under water, in water over shoulder depth.\n\n2-04. Leather-faced work gloves.--Leather-faced work gloves shall be worn when;\n(a) Handling wire rope;",

    # Page 2
    "(b) Handling sharp or rough steel or rock.\n\n(c) Sand blasting;\n\n(d) Handling molten metal (ie) babbit, etc;\n\n(e) The work being done requires protection greater than that afforded by cotton gloves.\n\n2-05. Rubber gloves shall be worn when:\n(a) Using creosote, caustic or acids;\n(b) Working with electricity - power lines or utility lines at locks where cut-off is not available. No work should be conducted unless authorized by the supervisors.\n\n2-06. Goggles shall be worn while using:\n(a) grinders or emory wheels,\n(b) jackhammers or chippers,\n(c) sand blast equipment where all operators are to wear hoods,\n(d) spray guns, or brushing above one's chest,",

    # Page 3
    "(e) Creosote paint, caustics, etc., and will be used in any place where there is danger of a flying particle striking an employee's eye.\n(f) Sterilize goggles in alcohol before issuing to another employee.\n\n2-07. Hood with air supply hose shall be worn:\n(a) When sandblasting in confined area, where air currents cannot supply fresh air and keep excessive dust blown away and;\n(b) when painting in any confined area, where air currents cannot supply fresh air and keep excessive fumes blown away.\n\n2-08. Welders hoods, sleeves and gloves shall be worn whenever welding is done by the electric arc method, when working overhead with acetylene torch, and when babbiting or soldering.\n\n2-09. Life belts with suitable safety line shall be worn by all employees, when danger of falling is a hazard to be encountered. A few reminders as to wearing and care are as follows:\n(a) Wear life belt when oiling or repairing masts of derricks or dipper dredges, etc.",

    # Page 4
    "(b) All personnel should wear life belts when working from ladders in valve pits, etc.\n(c) When working on dam wickets.\n(d) Life belts may be worn when working on lock gates in place of safety jackets.\n(e) Belts should be inspected each day.\n(f) Never punch extra holes in safety belts; get one that fits.\n(g) Do not throw belts on walls, floors or ground.\n(h) Belts should be cleaned and wiped dry at the end of each day's use.\n(i) Leather belts should be oiled regularly with Neats foot oil or any approved leather dressing. (Never oil a leather object with cylinder oil).\n\n2-10. Life jackets shall be worn by all employees performing work where there is a chance of falling, slipping or being pushed or thrown into the water - such as\n(a) on lock walls, at hand operated locks, when one man is making a lockage at night,",

    # Page 5
    "(b) when making repairs near the edge of lock wall,\n(c) when working on the deck of dredges, barges or derrick boats,\n(d) when drilling or sounding from the deck of boats or flats,\n(e) working on lock gates,\n(f) raising or lowering wickets,\n(g) working on steep river banks,\n(h) while in any skiff or launch.\n\n2-11. Respirators shall be worn while\n(a) using spray gun,\n(b) sandblasting in the open,\n(c) painting in interiors when ventilation is poor,\n(d) cleaning scale from inside of boilers, and\n(e) whenever and wherever there is an extraordinary amount of dust in the air, and air hoods are not required,",

    # Page 6
    "2-12. Safety hats shall be worn - (a) Whenever employees are working below other employees or plant in valve pits or lock chambers on construction or repair work, etc., where there is danger of being struck by falling objects.\n\n2-13. Safety foot guards, or shoes.--\n(a) Foot guards are standard equipment and shall be worn by all employees working in boatyard, machine shops, or on any repair work, or field work where heavy objects are being moved or lifted from the floor or ground, unless the employee is wearing safety shoes. Several instances of such work are - handling rock; placing buoys and weights; installing or replacing machinery; storing supplies, etc.\n(b) Safety shoes are not furnished by the Government, but are recommended by the Department. They are manufactured by several leading shoe companies, and can be purchased for the same price as a good work shoe. They are comfortable, long wearing shoes, and provide the nearest thing to absolute toe and arch protection now available on the market.\n\n2-14. Equipment General.--No employee shall use defective tools or equipment. Mushroomed heads on chisels, etc; cracked hammer",

    # Page 7
    "or axe handles; loose heads, as on axes, mauls, etc; frayed rope; or weakened wire rope should be reported to the supervisor and laid aside where they cannot be used. Never use a tool in any manner, or in doing a task, for which it was not intended. Small tools should be held by means of tongs when being struck by a second person. When not in use all tools should be stored in the tool locker or on the tool board provided for them. Always examine equipment before using.\n\n2-15. Adzes and machetes.--(a) Store, and carry these tools in a sheathe, in the same manner as an axe.\n(b) Never use an adze on a loose board; work in a clear space; concentrate on your work; and never chop towards your foot.\n(c) Never use a machete in a cramped position; chop away from the body; watch for approaching employees. Watch for overhead vines and limbs. Do not use a machete in any place where the footing is not secure. Keep right leg forward if using machete in right hand and left leg forward if using in left hand.\n\n2-16. Axes.--(a) 1. General.--When not in use they shall be stored in racks or fastened to the wall in such manner that they cannot shake loose and fall.",

    # Page 8
    "2. When being carried in a vehicle the blade should be encased, so that no part of the sharpened edge is exposed. Only single edge axes are recommended for use; and if being carried on the job should be shouldered with the blunt end toward the neck.\n\n3. Hazards to be avoided when chopping are overhanging limbs and vines; chopping towards feet, or other parts of the body; approach of other employees; flying chips; loose heads; dull blades; and above all uncertain footing should be avoided.\n\n(b) Hand axes.--1. Heads should be single blade, carried in a sheathe provided with belt loop and fastener to prevent the axe from falling out. The cutting edge should be kept sharp and clean at all times. It should be solidly wedged on the handle.\n\n2. Handles shall be straight, sound, clear and free from defects.\n\n3. Use.--Never throw an axe. Never chop toward the body. Do not use an axe in a confined or crowded area. Be alert for approaching employees. If it becomes necessary to clear out overhead branches out of reach from the ground, the axe should be carried up the tree in the belt sheathe, on the belt; or preferably, raised by means of a handy line.",

    # Page 9
    "(c) Pole axes.--1. Heads should be single bit and solidly wedged to the handle. The cutting edge should be kept sharp and clean at all times.\n2. Handles shall be straight, sound, clear and free from defects.\n3. Use.--A pole axe should not be used as a sledge hammer, as it will spread the eye, causing the handle to become loose and dangerous. Before using a pole axe be certain that there is no brush to obstruct a clear swing. Look the tree over for any dead limbs that may become disengaged during the chopping or felling of the tree. Make a deep \"V\" grooved notch on the side that the tree is to fall. This will prevent kick backs. Axe should be carried on shoulder with the cutting edge away from neck.\n\n(d) Double-Bit axes.--1. Heads are double-bladed and should be solidly wedged to the handle. The cutting edges should be kept sharp and clean. Excessive grinding on one edge will cause the axe to become unbalanced and dangerous.\n2. Handles shall be straight, sound, clear, and free from defects.\n3. Use.--A double-bit axe should never be used on the side, as a hammer, to drive wedges or stakes. Double-bit axes are",

    # Page 10
    "not recommended, but when necessary shall be used only by experienced axemen. Never work in confined areas. Clear away all brush, low limbs and obstructing vines.\n\n2-17. Chains.--(a) Examination.--1. Inspect every link in a chain whenever the chain has not been used for a considerable length of time, or, whenever the chain is to be used for heavy lifting that will strain the capacity of the chain.\n2. Check the hook and ring for weakness, spread or crimp.\n(b) Use.--1. Do not overload a chain.\n2. Never put hands between a chain and the object it is wrapped around.\n3. Never repair chain with wire. (Use a cold shut or similar repair link).\n4. Wrap chain around object, and fasten. Do not lift object with hook, unless special fastenings are used. Tie hook securely so that it will not come loose, or slip.\n\n2-18. Chisels.--(a) Wood chisels should never be used except for the purpose they are intended and should never be directed towards the body. Use wooden mallets; see",

    # Page 11
    "that handle and point are solid and in good repair; keep the cutting edge sharp and true.\n\n(b) Cold chisels.--Cold chisels should be checked for defects before use. Chisels with mushroomed heads, broken points and cracked shanks should be removed from service until properly repaired. Never direct the point toward the body. Use proper hammer; keep the cutting edge sharp.\n\n2-19. Drills.--Drills for drilling into masonry or rock should never be used for crow bars. Shanks must be straight; cutting edges sharp; and heads flat without mushrooms.\n\n2-20. Files.--Files shall be provided with handles. Whenever the material being filed is fastened in a machine or being turned by mechanical means, the operator should roll up his sleeves, and remove tie if one is being worn.\n\n2-21. Fire Extinguishers.--(a) General.--Extinguishers shall be located by the Safety Section in readily accessible places, and shall be examined every month. The initials of the examiner shall be placed on the card with the date of each examination.\n\n(b) Carbon Tetrachloride extinguishers shall be placed on all floating plant and houses, storehouses and garages, trucks and passenger cars. Keep recharges on hand for",

    # Page 12
    "each type. It is to be used on indoor fires in wood textiles, paper, rubbish, etc. It is not so effective outdoors where wind strikes the fire. It is fairly effective on all types of fire except electrical.\n\n(c) CO2 extinguishers shall be placed in all floating plant, where highly inflammable materials are stored, ie, gasoline, paint, etc. They shall be tested by weighing every six months and if more than one pound under-weight shall be recharged immediately. This is the best type for fires involving oil, grease, paint, lacquer, etc., where the smothering action is effective.\n\n(d) Soda-acid extinguishers which contain water as an extinguishing agent, and soda and sulphuric acid as the pressure agent to expel the water through the hose, WILL FREEZE and must be kept in protected places where the temperature will not be below 32 Fahrenheit. These extinguishers are for use in fighting fires in free burning material such as wood, paper, rubbish, etc. Under no circumstances should they be used for electrical fires because the water conducts the current back to the body of the operator. A sign will be placed on the soda acid extinguisher to this effect. These extinguishers shall be refilled once each year and immediately after being discharged in case of emergency. To keep the nozzle clear,",

    # Page 13
    "wire shall be run through nozzle at least once each month.\n\n2-22. Hammers and mauls.--(a) Keep the heads dressed, never use a mushroomed, battered, or chipped tool.\n(b) Use bronze, babbitt or wooden mallet for striking metal parts such as tapping keys out of drill chucks, when sustained hammering is unnecessary.\n(c) Check handles and fastenings of heads before using.\n(d) Keep eyes on work.\n\n2-23. Jacks.--(a) Overload should never be placed on a jack.\n(b) Footing.--Always place a jack on a solid, level footing.\n(c) Blocking.--Keep blocking on each side of load center to within 1\" of jack height.\n(d) Don't get under loads supported only by a jack, without blocking.\n\n2-24. Ladders.--(a) General.--Ladders should never be painted. Use linseed oil or clear varnish.\n(b) Climbing ladders.--1. Examine for defects before using.",

    # Page 14
    "2. Use ladder with safety feet, and if floor is hard or slippery tie ladder at base or have someone hold it.\n3. Place base of ladder about 1/4 of length from wall.\n4. Face ladder and hold on to side rails with both hands, whether ascending or descending.\n5. Clean soles of shoes before climbing.\n6. Never use a ladder in front of a doorway, unless door is locked or guarded.\n7. If rungs are slippery, clean off before raising the ladder.\n8. Carry all tools in suitable pockets, or hoist them in a sack with rope.\n\n(c) Step ladders.--1. Be certain that legs are fully extended.\n2. Lock the spreader.\n3. If footing is slippery block the feet.\n4. Avoid standing on top, use long enough ladder to stand at least 2 steps from",

    # Page 15
    "top.\n5. Never lay tools on ladder. A suitable box should be provided to hold tools.\n\n(d) Extension ladders.--1. Raising an extension ladder is a two man job.\n2. Raise ladder before extending it.\n3. Use rope or pole to extend ladder.\n4. When lowering, reverse the process.\n\n(e) Use of ladders.--1. Never use a ladder for a scaffold plank or walkway.\n2. Carry ladder with safety feet to the rear.\n3. When carrying a ladder alone, stand at the balance point of the weight, and elevate the front to a height above a person's head.\n4. If ceilings are low carry ladder at side.\n5. When two persons are carrying a ladder, they should stand as near the ends as possible.",

    # Page 16
    "6. Be careful not to strike anyone with the ladder.\n7. Never lean far out from any ladder.\n8. Use safety line when work requires it.\n9. Do not work from a ladder in a high wind.\n10. If working over a walkway, where people might be hit by falling objects, rope off the space around and under the ladder.\n\n2-25. Pneumatic tools.--Pneumatic tools shall never be pointed at a person.\n(a) Safety clips shall be fastened before using.\n(b) Protect the ear drums, before commencing work, in a confined area by placing cotton in ears.\n(c) Air hose shall not be pointed towards the body.\n(d) Do not use air hose for cleaning structures, unless all persons in vicinity have on goggles."
]

doc = pymupdf.open()
for text in pages_text:
    page = doc.new_page(width=595, height=842)
    rect = pymupdf.Rect(50, 50, 545, 792)
    page.insert_textbox(rect, text, fontsize=11, fontname="helv")

output_path = os.path.join("documents", "Apparel_Equipment_and_Materials.pdf")
doc.save(output_path)
doc.close()
print(f"Created {output_path} with {len(pages_text)} pages.")
